spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/lostory}
spring.datasource.username=${DB_USERNAME:lostory}
spring.datasource.password=${DB_PASSWORD:lostory}
spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
