spring.autoconfigure.exclude=org.springframework.boot.security.autoconfigure.UserDetailsServiceAutoConfiguration
spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
