spring.application.name=backend
spring.autoconfigure.exclude=org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration,org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration,org.springframework.boot.flyway.autoconfigure.FlywayAutoConfiguration,org.springframework.boot.security.autoconfigure.UserDetailsServiceAutoConfiguration
management.endpoints.web.exposure.include=health
server.port=${SERVER_PORT:8080}
