ALTER TABLE found_items
    DROP CONSTRAINT found_items_handover_status_check,
    DROP CONSTRAINT found_items_storage_detail_check;

ALTER TABLE found_items
    ADD CONSTRAINT found_items_handover_status_check
        CHECK (handover_status IN ('NONE', 'USER_CONFIRMED', 'CENTER_CONFIRMED', 'LEGACY_UNVERIFIED')),
    ADD CONSTRAINT found_items_storage_detail_check
        CHECK (
            (status = 'DRAFT'
                AND storage_method IS NULL
                AND storage_description IS NULL
                AND legacy_handover_place_name IS NULL
                AND center_id IS NULL
                AND handover_status = 'NONE'
                AND handed_at IS NULL)
            OR
            (storage_method = 'LEFT_IN_PLACE'
                AND status IN ('ACTIVE', 'EXPIRED', 'RETURNED')
                AND storage_description IS NULL
                AND legacy_handover_place_name IS NULL
                AND center_id IS NULL
                AND handover_status = 'NONE'
                AND handed_at IS NULL)
            OR
            (storage_method = 'MOVED_TO_SAFE_PLACE'
                AND status IN ('ACTIVE', 'EXPIRED', 'RETURNED')
                AND storage_description IS NOT NULL
                AND btrim(storage_description) <> ''
                AND legacy_handover_place_name IS NULL
                AND center_id IS NULL
                AND handover_status = 'NONE'
                AND handed_at IS NULL)
            OR
            (storage_method = 'HANDED_TO_CENTER'
                AND storage_description IS NULL
                AND (
                    (status = 'PENDING_HANDOVER'
                        AND center_id IS NOT NULL
                        AND legacy_handover_place_name IS NULL
                        AND handover_status = 'NONE'
                        AND handed_at IS NULL)
                    OR
                    (status IN ('ACTIVE', 'EXPIRED', 'RETURNED')
                        AND center_id IS NOT NULL
                        AND legacy_handover_place_name IS NULL
                        AND handover_status IN ('USER_CONFIRMED', 'CENTER_CONFIRMED')
                        AND handed_at IS NOT NULL
                        AND handed_at BETWEEN created_at AND updated_at)
                    OR
                    (status IN ('ACTIVE', 'EXPIRED', 'RETURNED')
                        AND center_id IS NULL
                        AND legacy_handover_place_name IS NOT NULL
                        AND btrim(legacy_handover_place_name) <> ''
                        AND handover_status = 'LEGACY_UNVERIFIED'
                        AND handed_at IS NULL)
                ))
        );

CREATE TABLE center_handovers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    found_item_id BIGINT NOT NULL REFERENCES found_items(id) ON DELETE RESTRICT,
    center_id BIGINT NOT NULL REFERENCES lost_centers(id) ON DELETE RESTRICT,
    status TEXT NOT NULL,
    user_confirmed_at TIMESTAMPTZ NOT NULL,
    decided_at TIMESTAMPTZ,
    decided_by BIGINT REFERENCES users(id) ON DELETE RESTRICT,
    rejection_reason VARCHAR(1000),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    superseded_at TIMESTAMPTZ,
    CONSTRAINT center_handovers_status_check
        CHECK (status IN ('USER_CONFIRMED', 'CENTER_CONFIRMED', 'REJECTED')),
    CONSTRAINT center_handovers_decision_check CHECK (
        (status = 'USER_CONFIRMED' AND decided_at IS NULL AND decided_by IS NULL AND rejection_reason IS NULL)
        OR (status = 'CENTER_CONFIRMED' AND decided_at IS NOT NULL AND decided_by IS NOT NULL
            AND rejection_reason IS NULL)
        OR (status = 'REJECTED' AND decided_at IS NOT NULL AND decided_by IS NOT NULL
            AND rejection_reason IS NOT NULL AND btrim(rejection_reason) <> '')
    )
);

CREATE UNIQUE INDEX center_handovers_one_current_item_uq
    ON center_handovers (found_item_id) WHERE superseded_at IS NULL;
CREATE INDEX center_handovers_center_queue_idx
    ON center_handovers (center_id, status, user_confirmed_at, id) WHERE superseded_at IS NULL;

INSERT INTO center_handovers (found_item_id, center_id, status, user_confirmed_at, created_at)
SELECT id, center_id, 'USER_CONFIRMED', handed_at, handed_at
FROM found_items
WHERE handover_status = 'USER_CONFIRMED'
  AND storage_method = 'HANDED_TO_CENTER'
  AND center_id IS NOT NULL
  AND handed_at IS NOT NULL;
