CREATE TABLE report_waypoints (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id BIGINT NOT NULL REFERENCES lost_reports(id) ON DELETE CASCADE,
    ordinal SMALLINT NOT NULL,
    place_name TEXT,
    location GEOGRAPHY(Point, 4326) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_report_waypoints_report_ordinal UNIQUE (report_id, ordinal),
    CONSTRAINT report_waypoints_ordinal_check CHECK (ordinal BETWEEN 1 AND 10),
    CONSTRAINT report_waypoints_place_name_check CHECK (place_name IS NULL OR btrim(place_name) <> '')
);
