CREATE TABLE match_candidates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id BIGINT NOT NULL REFERENCES lost_reports(id) ON DELETE CASCADE,
    item_id BIGINT NOT NULL REFERENCES found_items(id) ON DELETE RESTRICT,
    rank SMALLINT NOT NULL,
    score NUMERIC(5, 2) NOT NULL,
    score_breakdown JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_match_candidates_report_rank UNIQUE (report_id, rank),
    CONSTRAINT uk_match_candidates_report_item UNIQUE (report_id, item_id),
    CONSTRAINT match_candidates_rank_check CHECK (rank BETWEEN 1 AND 5),
    CONSTRAINT match_candidates_score_check CHECK (score BETWEEN 0 AND 100),
    CONSTRAINT match_candidates_score_breakdown_check CHECK (jsonb_typeof(score_breakdown) = 'object')
);

CREATE INDEX match_candidates_item_idx
    ON match_candidates (item_id);
