CREATE TABLE point_ledger (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    entry_type TEXT NOT NULL,
    amount INTEGER NOT NULL,
    idempotency_key UUID NOT NULL UNIQUE,
    reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT point_ledger_amount_check CHECK (
        (entry_type = 'DEMO_GRANT' AND amount > 0)
        OR (entry_type = 'CANDIDATE_ACCESS_DEBIT' AND amount < 0)
        OR (entry_type = 'ADMIN_ADJUSTMENT' AND amount <> 0)
    ),
    CONSTRAINT point_ledger_reason_check CHECK (
        entry_type <> 'ADMIN_ADJUSTMENT' OR (reason IS NOT NULL AND btrim(reason) <> '')
    )
);

CREATE INDEX point_ledger_user_created_idx
    ON point_ledger (user_id, created_at DESC);
