CREATE TABLE candidate_accesses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    debit_transaction_id BIGINT NOT NULL UNIQUE,
    unlocked_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_candidate_accesses_report UNIQUE (report_id),
    CONSTRAINT fk_candidate_accesses_report_user FOREIGN KEY (report_id, user_id)
        REFERENCES lost_reports(id, reporter_id) ON DELETE CASCADE,
    CONSTRAINT fk_candidate_accesses_debit_transaction FOREIGN KEY (debit_transaction_id)
        REFERENCES point_ledger(id) ON DELETE RESTRICT
);

CREATE INDEX candidate_accesses_user_unlocked_idx
    ON candidate_accesses (user_id, unlocked_at DESC);
