CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    action TEXT NOT NULL,
    target_type TEXT,
    target_id BIGINT,
    metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT audit_logs_action_check CHECK (action ~ '^[A-Z][A-Z0-9_]{2,63}$'),
    CONSTRAINT audit_logs_target_check CHECK (
        (target_type IS NULL AND target_id IS NULL)
        OR (target_type IS NOT NULL AND target_id IS NOT NULL)
    ),
    CONSTRAINT audit_logs_metadata_check CHECK (jsonb_typeof(metadata_json) = 'object')
);

CREATE INDEX audit_logs_actor_time_idx
    ON audit_logs (user_id, occurred_at DESC);

CREATE INDEX audit_logs_target_time_idx
    ON audit_logs (target_type, target_id, occurred_at DESC);
