CREATE TABLE center_partnerships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    center_id BIGINT NOT NULL REFERENCES lost_centers(id) ON DELETE RESTRICT,
    manager_email TEXT NOT NULL,
    manager_display_name TEXT NOT NULL,
    status TEXT NOT NULL,
    manager_user_id BIGINT REFERENCES users(id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    activated_at TIMESTAMPTZ,
    CONSTRAINT center_partnerships_status_check
        CHECK (status IN ('PENDING', 'PENDING_ACTIVATION', 'ACTIVE')),
    CONSTRAINT center_partnerships_email_normalized_check
        CHECK (manager_email = lower(btrim(manager_email)) AND manager_email <> ''),
    CONSTRAINT center_partnerships_display_name_check CHECK (btrim(manager_display_name) <> ''),
    CONSTRAINT center_partnerships_active_manager_check
        CHECK ((status = 'ACTIVE') = (manager_user_id IS NOT NULL AND activated_at IS NOT NULL))
);

CREATE INDEX center_partnerships_center_idx ON center_partnerships (center_id);
CREATE INDEX center_partnerships_manager_email_idx ON center_partnerships (manager_email);
CREATE UNIQUE INDEX center_partnerships_one_active_center_uq
    ON center_partnerships (center_id) WHERE status = 'ACTIVE';
CREATE UNIQUE INDEX center_partnerships_one_active_manager_uq
    ON center_partnerships (manager_email) WHERE status = 'ACTIVE';

CREATE TABLE center_activation_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partnership_id BIGINT NOT NULL REFERENCES center_partnerships(id) ON DELETE RESTRICT,
    token_hash BYTEA NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ,
    replaced BOOLEAN NOT NULL DEFAULT FALSE,
    issued_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT center_activation_tokens_hash_check CHECK (octet_length(token_hash) = 32),
    CONSTRAINT center_activation_tokens_expiry_check CHECK (expires_at > issued_at)
);

CREATE UNIQUE INDEX center_activation_tokens_hash_uq ON center_activation_tokens (token_hash);
CREATE INDEX center_activation_tokens_partnership_idx ON center_activation_tokens (partnership_id);
CREATE UNIQUE INDEX center_activation_tokens_one_current_uq
    ON center_activation_tokens (partnership_id)
    WHERE consumed_at IS NULL AND replaced = FALSE;
