CREATE TABLE return_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    handover_id BIGINT NOT NULL REFERENCES center_handovers(id) ON DELETE RESTRICT,
    found_item_id BIGINT NOT NULL REFERENCES found_items(id) ON DELETE RESTRICT,
    lost_report_id BIGINT NOT NULL REFERENCES lost_reports(id) ON DELETE RESTRICT,
    finder_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    center_id BIGINT NOT NULL REFERENCES lost_centers(id) ON DELETE RESTRICT,
    recorded_by BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    status TEXT NOT NULL DEFAULT 'RETURNED',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_return_records_handover UNIQUE (handover_id),
    CONSTRAINT uk_return_records_found_item UNIQUE (found_item_id),
    CONSTRAINT uk_return_records_lost_report UNIQUE (lost_report_id),
    CONSTRAINT return_records_status_check CHECK (status = 'RETURNED')
);

CREATE INDEX return_records_center_created_idx
    ON return_records (center_id, created_at DESC);
