ALTER TABLE center_activation_tokens
    ADD CONSTRAINT center_activation_tokens_id_partnership_uq UNIQUE (id, partnership_id);

CREATE TABLE partner_activation_delivery_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partnership_id BIGINT NOT NULL REFERENCES center_partnerships(id) ON DELETE RESTRICT,
    activation_token_id BIGINT NOT NULL,
    ciphertext BYTEA NOT NULL,
    nonce BYTEA NOT NULL,
    key_version VARCHAR(64) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    superseded_at TIMESTAMPTZ,
    CONSTRAINT partner_activation_delivery_token_fk
        FOREIGN KEY (activation_token_id, partnership_id)
        REFERENCES center_activation_tokens(id, partnership_id) ON DELETE RESTRICT,
    CONSTRAINT partner_activation_delivery_token_uq UNIQUE (activation_token_id),
    CONSTRAINT partner_activation_delivery_ciphertext_check CHECK (octet_length(ciphertext) > 16),
    CONSTRAINT partner_activation_delivery_nonce_check CHECK (octet_length(nonce) = 12),
    CONSTRAINT partner_activation_delivery_key_version_check CHECK (btrim(key_version) <> ''),
    CONSTRAINT partner_activation_delivery_expiry_check CHECK (expires_at > created_at)
);

CREATE UNIQUE INDEX partner_activation_delivery_one_current_uq
    ON partner_activation_delivery_outbox (partnership_id) WHERE superseded_at IS NULL;
