CREATE TABLE found_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    finder_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,

    name VARCHAR(100) NOT NULL,
    category VARCHAR(64) NOT NULL,
    description VARCHAR(1000) NOT NULL,

    found_at TIMESTAMPTZ NOT NULL,
    found_location_text VARCHAR(255) NOT NULL,

    storage_method VARCHAR(30) NOT NULL,
    storage_description VARCHAR(1000),
    handover_place_name VARCHAR(100),

    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expired_at TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '14 days'),

    CONSTRAINT found_items_category_not_blank_check
        CHECK (btrim(category) <> ''),

    CONSTRAINT found_items_name_not_blank_check
        CHECK (btrim(name) <> ''),

    CONSTRAINT found_items_description_not_blank_check
        CHECK (btrim(description) <> ''),

    CONSTRAINT found_items_location_not_blank_check
        CHECK (btrim(found_location_text) <> ''),

    CONSTRAINT found_items_storage_method_check
        CHECK (storage_method IN ('LEFT_IN_PLACE', 'MOVED_TO_SAFE_PLACE', 'HANDED_TO_CENTER')),

    CONSTRAINT found_items_status_check
        CHECK (status IN ('ACTIVE', 'CLOSED')),

    CONSTRAINT found_items_storage_detail_check
        CHECK (
            (
                storage_method = 'LEFT_IN_PLACE'
                AND storage_description IS NULL
                AND handover_place_name IS NULL
            )
            OR
            (
                storage_method = 'MOVED_TO_SAFE_PLACE'
                AND storage_description IS NOT NULL
                AND btrim(storage_description) <> ''
                AND handover_place_name IS NULL
            )
            OR
            (
                storage_method = 'HANDED_TO_CENTER'
                AND storage_description IS NULL
                AND handover_place_name IS NOT NULL
                AND btrim(handover_place_name) <> ''
            )
        )
);

CREATE INDEX found_items_created_idx
    ON found_items (created_at DESC);

CREATE INDEX found_items_finder_created_idx
    ON found_items (finder_id, created_at DESC);

CREATE INDEX found_items_status_created_idx
    ON found_items (status, created_at DESC);

CREATE INDEX idx_found_items_expired_at
    ON found_items (expired_at);