CREATE TABLE found_item_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    found_item_id BIGINT NOT NULL REFERENCES found_items(id) ON DELETE CASCADE,

    original_filename VARCHAR(255) NOT NULL,
    stored_filename VARCHAR(255) NOT NULL,
    storage_path VARCHAR(500) NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    size_bytes BIGINT NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT found_item_images_original_filename_not_blank_check
        CHECK (btrim(original_filename) <> ''),

    CONSTRAINT found_item_images_stored_filename_not_blank_check
        CHECK (btrim(stored_filename) <> ''),

    CONSTRAINT found_item_images_storage_path_not_blank_check
        CHECK (btrim(storage_path) <> ''),

    CONSTRAINT found_item_images_content_type_check
        CHECK (content_type IN ('image/jpeg', 'image/png', 'image/webp')),

    CONSTRAINT found_item_images_size_positive_check
        CHECK (size_bytes > 0),

    CONSTRAINT found_item_images_size_max_check
        CHECK (size_bytes <= 5242880)
);

CREATE INDEX found_item_images_found_item_id_created_idx
    ON found_item_images (found_item_id, created_at ASC);