CREATE TABLE lost_centers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    center_key VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(150) NOT NULL,
    parent_place VARCHAR(100),
    phone_number VARCHAR(100),
    address VARCHAR(255) NOT NULL,
    detail_location VARCHAR(255),

    location GEOGRAPHY(POINT, 4326) NOT NULL,

    operating_hours VARCHAR(255),
    handoff_available VARCHAR(20) NOT NULL,
    verification_status VARCHAR(80) NOT NULL,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_lost_centers_location
    ON lost_centers
    USING GIST (location);

CREATE INDEX idx_lost_centers_is_active
    ON lost_centers (is_active);

CREATE INDEX idx_lost_centers_handoff_available
    ON lost_centers (handoff_available);

CREATE INDEX idx_lost_centers_verification_status
    ON lost_centers (verification_status);