CREATE TABLE lost_centers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_key TEXT UNIQUE,
    name TEXT NOT NULL,
    address TEXT NOT NULL,
    location GEOGRAPHY(Point, 4326) NOT NULL,
    contact_phone TEXT NOT NULL,
    operating_hours TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT lost_centers_name_not_blank_check CHECK (btrim(name) <> ''),
    CONSTRAINT lost_centers_address_not_blank_check CHECK (btrim(address) <> ''),
    CONSTRAINT lost_centers_contact_phone_trimmed_check CHECK (contact_phone = btrim(contact_phone))
);

CREATE INDEX lost_centers_active_location_gix
    ON lost_centers USING GIST (location)
    WHERE is_active;
