CREATE TABLE item_features (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id BIGINT NOT NULL REFERENCES found_items(id) ON DELETE CASCADE,
    kind TEXT NOT NULL,
    feature_value TEXT NOT NULL,
    ordinal SMALLINT NOT NULL DEFAULT 1,
    source TEXT NOT NULL,
    visibility TEXT NOT NULL DEFAULT 'MATCH_ONLY',
    confidence NUMERIC(4, 3),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_item_features_item_kind_source_ordinal UNIQUE (item_id, kind, source, ordinal),
    CONSTRAINT item_features_kind_check CHECK (kind IN ('COLOR', 'BRAND', 'PUBLIC_DESCRIPTION', 'OCR_TEXT')),
    CONSTRAINT item_features_visibility_check CHECK (visibility IN ('MATCH_ONLY', 'CANDIDATE_VIEW')),
    CONSTRAINT item_features_source_check CHECK (source IN ('FINDER', 'AI', 'SYSTEM')),
    CONSTRAINT item_features_confidence_check CHECK (confidence IS NULL OR confidence BETWEEN 0 AND 1),
    CONSTRAINT item_features_ordinal_check CHECK (ordinal BETWEEN 1 AND 20),
    CONSTRAINT item_features_value_not_blank_check CHECK (btrim(feature_value) <> '')
);
