CREATE TABLE lost_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    category VARCHAR(64) NOT NULL,
    lost_at_from TIMESTAMPTZ NOT NULL,
    lost_at_to TIMESTAMPTZ NOT NULL,
    description TEXT NOT NULL,
    search_radius INTEGER NOT NULL DEFAULT 1000,
    status TEXT NOT NULL DEFAULT 'OPEN',
    expired_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_lost_reports_id_reporter UNIQUE (id, reporter_id),
    CONSTRAINT lost_reports_category_not_blank_check CHECK (btrim(category) <> ''),
    CONSTRAINT lost_reports_description_check CHECK (btrim(description) <> '' AND char_length(description) <= 1000),
    CONSTRAINT lost_reports_period_check CHECK (lost_at_from <= lost_at_to),
    CONSTRAINT lost_reports_search_radius_check CHECK (search_radius BETWEEN 100 AND 3000),
    CONSTRAINT lost_reports_status_check CHECK (status IN ('OPEN', 'CLOSED', 'EXPIRED')),
    CONSTRAINT lost_reports_expired_at_check CHECK (expired_at > created_at)
);

CREATE INDEX lost_reports_reporter_created_idx
    ON lost_reports (reporter_id, created_at DESC);
